# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Members
    url: '#people'
    weight: 50
  - name: Research
    url: '#research'
    weight: 60
  - name: Projects
    url: '#projects'
    weight: 70
  - name: Resources
    url: '#resources'
    weight: 80
  - name: Publications
    url: '#publications'
    weight: 90
  #- name: Talks
  #  url: '#talks'
  #  weight: 70    
  - name: News
    url: '#news'
    weight: 100    
  - name: Contact
    url: '#contact'
    weight: 110

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
